import {
  ShoppingCart,
  Utensils,
  Home,
  Car,
  Heart,
  Gift,
  PiggyBank,
  DollarSign,
  CreditCard,
  Briefcase,
  GraduationCap,
  Plane,
  Apple,
  Beer,
  Shirt,
  Wifi,
  Phone,
  Lightbulb,
  Droplet,
  Book,
  Music,
  Film,
  Gamepad2,
  PawPrint,
  Leaf,
  Star,
  Wrench,
  ClipboardList,
  Coins,
  ReceiptText,
  Banknote,
  Fuel,
  Bus,
  TrainFront,
  Truck,
  ShoppingBag,
  ShoppingBasket,
  Salad,
  Cake,
  Coffee,
  Pizza,
  Wine,
  Candy,
  Carrot,
  Fish,
  Egg,
  Soup,
  IceCreamCone,
  Popcorn,
  Sandwich,
  Cookie,
  Hamburger,
  CupSoda,
  Banana,
  Grape,
  Drumstick,
  Shrimp,
  Milk,
  Croissant,
  Donut,
  Lollipop
} from "lucide-react";

export const ICONES_CATEGORIAS = {
  alimentacao: Utensils,
  casa: Home,
  transporte: Car,
  saude: Heart,
  presente: Gift,
  poupanca: PiggyBank,
  salario: DollarSign,
  cartao: CreditCard,
  trabalho: Briefcase,
  educacao: GraduationCap,
  viagem: Plane,
  mercado: ShoppingCart,
  restaurante: Utensils,
  frutas: Apple,
  bebidas: Beer,
  roupas: Shirt,
  internet: Wifi,
  telefone: Phone,
  energia: Lightbulb,
  agua: Droplet,
  livros: Book,
  musica: Music,
  filmes: Film,
  jogos: Gamepad2,
  pet: PawPrint,
  natureza: Leaf,
  lazer: Star,
  ferramentas: Wrench,
  lista: ClipboardList,
  investimentos: Coins,
  recibo: ReceiptText,
  dinheiro: Banknote,
  combustivel: Fuel,
  onibus: Bus,
  trem: TrainFront,
  caminhão: Truck,
  sacola: ShoppingBag,
  cesta: ShoppingBasket,
  salada: Salad,
  bolo: Cake,
  cafe: Coffee,
  pizza: Pizza,
  vinho: Wine,
  doce: Candy,
  cenoura: Carrot,
  peixe: Fish,
  ovo: Egg,
  sopa: Soup,
  sorvete: IceCreamCone,
  pipoca: Popcorn,
  sanduiche: Sandwich,
  biscoito: Cookie,
  hamburguer: Hamburger,
  refrigerante: CupSoda,
  banana: Banana,
  uva: Grape,
  frango: Drumstick,
  camarao: Shrimp,
  leite: Milk,
  croissant: Croissant,
  donut: Donut,
  pirulito: Lollipop
};
