export { default as Header } from './header';
export { default as HeroSection } from './hero-section';
export { default as FeaturesSection } from './features-section';
export { default as WhatsAppSection } from './whatsapp-section';
export { default as PricingSection } from './pricing-section';
export { default as CTASection } from './cta-section';
export { default as ContactSection } from './contact-section';
export { default as Footer } from './footer';
export { default as LandingClient } from './landing-client'; 